// scripts/app-templates/solid/src/App.jsx
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import {
  createAppTranslator,
  getAppLocale,
  languageStorageKey,
  localeEventName,
  normalizeLocale,
  resources,
} from "./i18n/index.js";

const App = (props) => {
  const [themeId, setThemeId] = createSignal(props.sdk?.theme?.activeThemeId || "light");
  const [locale, setLocale] = createSignal(getAppLocale(props.sdk));
  const t = createMemo(() => createAppTranslator(resources, locale().language));

  onMount(() => {
    const themeCleanup = props.sdk?.onThemeChange?.((theme) => {
      setThemeId(theme.activeThemeId);
    });
    const updateLocale = (nextLocale) => setLocale(normalizeLocale(nextLocale));
    const localeCleanup = props.sdk?.onLocaleChange?.(updateLocale);
    let eventCleanup = !localeCleanup && !props.sdk?.onLocaleChange
      ? props.sdk?.events?.on?.("locale:change", updateLocale)
      : undefined;
    if (!props.sdk && typeof window !== "undefined") {
      const handleLocaleEvent = (event) => updateLocale(event.detail);
      const handleStorage = (event) => {
        if (event.key === languageStorageKey) {
          updateLocale({ language: event.newValue, direction: "ltr" });
        }
      };
      window.addEventListener(localeEventName, handleLocaleEvent);
      window.addEventListener("storage", handleStorage);
      eventCleanup = () => {
        window.removeEventListener(localeEventName, handleLocaleEvent);
        window.removeEventListener("storage", handleStorage);
      };
    }
    onCleanup(() => {
      themeCleanup?.();
      localeCleanup?.();
      eventCleanup?.();
    });
  });

  const copyText = () => {
    if (!props.sdk) return t()("copy.standalone");
    return props.mode === "settings" ? t()("copy.settings") : t()("copy.host");
  };

  return (
    <div class={`app-shell ${themeId() === "dark" ? "is-dark" : ""}`}>
      <div class="app-kicker">{props.mode === "settings" ? t()("label.settings") : t()("label.app")}</div>
      <div class="app-title">__APP_DISPLAY_NAME__</div>
      {props.mode !== "icon" && props.mode !== "appIcon" && (
        <p class="app-copy">{copyText()}</p>
      )}
    </div>
  );
};

export default App;

// scripts/app-templates/vue/src/App.vue
<script setup>
import { computed, onMounted, onUnmounted, ref } from "vue";
import {
  createAppTranslator,
  getAppLocale,
  languageStorageKey,
  localeEventName,
  normalizeLocale,
  resources,
} from "./i18n/index.js";

const props = defineProps({
  mode: { type: String, default: "icon" },
  sdk: { type: Object, default: null },
});

const themeId = ref(props.sdk?.theme?.activeThemeId || "light");
const locale = ref(getAppLocale(props.sdk));
const t = computed(() => createAppTranslator(resources, locale.value.language));
const isIcon = computed(() => props.mode === "icon" || props.mode === "appIcon");
const isSettings = computed(() => props.mode === "settings");
const copyText = computed(() => {
  if (!props.sdk) return t.value("copy.standalone");
  return isSettings.value ? t.value("copy.settings") : t.value("copy.host");
});
let themeCleanup;
let localeCleanup;
let eventCleanup;

onMounted(() => {
  themeCleanup = props.sdk?.onThemeChange?.((theme) => {
    themeId.value = theme.activeThemeId;
  });
  const updateLocale = (nextLocale) => {
    locale.value = normalizeLocale(nextLocale);
  };
  localeCleanup = props.sdk?.onLocaleChange?.(updateLocale);
  if (!localeCleanup && !props.sdk?.onLocaleChange) {
    eventCleanup = props.sdk?.events?.on?.("locale:change", updateLocale);
  }
  if (!props.sdk && typeof window !== "undefined") {
    const handleLocaleEvent = (event) => updateLocale(event.detail);
    const handleStorage = (event) => {
      if (event.key === languageStorageKey) {
        updateLocale({ language: event.newValue, direction: "ltr" });
      }
    };
    window.addEventListener(localeEventName, handleLocaleEvent);
    window.addEventListener("storage", handleStorage);
    eventCleanup = () => {
      window.removeEventListener(localeEventName, handleLocaleEvent);
      window.removeEventListener("storage", handleStorage);
    };
  }
});

onUnmounted(() => {
  themeCleanup?.();
  localeCleanup?.();
  eventCleanup?.();
});
</script>

<template>
  <div class="app-shell" :class="{ 'is-dark': themeId === 'dark' }">
    <div class="app-kicker">{{ isSettings ? t("label.settings") : t("label.app") }}</div>
    <div class="app-title">__APP_DISPLAY_NAME__</div>
    <p v-if="!isIcon" class="app-copy">
      {{ copyText }}
    </p>
  </div>
</template>
