// scripts/widget-templates/solid/src/Widget.jsx
import { createSignal, onCleanup, onMount } from "solid-js";

const Widget = (props) => {
  const [themeId, setThemeId] = createSignal(props.sdk?.theme?.activeThemeId || "light");

  onMount(() => {
    const cleanup = props.sdk?.onThemeChange?.((theme) => {
      setThemeId(theme.activeThemeId);
    });
    onCleanup(() => cleanup?.());
  });

  return (
    <div class={`widget-shell ${themeId() === "dark" ? "is-dark" : ""}`}>
      <div class="widget-kicker">Solid Widget</div>
      <div class="widget-title">__WIDGET_DISPLAY_NAME__</div>
      {props.mode !== "icon" && (
        <p class="widget-copy">通过 props.sdk 获取宿主能力，支持 icon/full 两种模式。</p>
      )}
    </div>
  );
};

export default Widget;

// scripts/widget-templates/react/src/Widget.tsx
import { useEffect, useState } from "react";
import type { WidgetProps } from "./types";

const Widget = ({ mode = "icon", sdk }: WidgetProps) => {
  const [themeId, setThemeId] = useState(sdk?.theme?.activeThemeId || "light");

  useEffect(() => {
    if (!sdk?.onThemeChange) return undefined;
    return sdk.onThemeChange((theme) => setThemeId(theme.activeThemeId));
  }, [sdk]);

  const isIcon = mode === "icon";
  const shellClassName = [
    "tw:box-border tw:flex tw:h-full tw:w-full tw:flex-col tw:justify-center tw:gap-2 tw:overflow-hidden tw:rounded-2xl tw:p-[14px]",
    themeId === "dark"
      ? "tw:bg-[linear-gradient(135deg,#064e3b_0%,#022c22_100%)] tw:text-emerald-100"
      : "tw:bg-[linear-gradient(135deg,#d1fae5_0%,#a7f3d0_100%)] tw:text-emerald-950",
  ].join(" ");

  return (
    <div className={shellClassName}>
      <div className="tw:text-[11px] tw:font-bold tw:uppercase tw:tracking-[0.08em] tw:opacity-75">React Widget</div>
      <div className="tw:text-[22px] tw:font-extrabold tw:leading-tight">__WIDGET_DISPLAY_NAME__</div>
      {!isIcon && <p className="tw:m-0 tw:text-[13px] tw:leading-normal tw:opacity-80">通过 props.sdk 获取宿主能力，支持 icon/full 两种模式。</p>}
    </div>
  );
};

export default Widget;
